version: '3.7'

services:  
  perfex:
    image: perfexcrm
    volumes:
      - /root/Perfex-CRM:/var/www/html
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.4'
          memory: 256M
      labels:
        - traefik.enable=true
        - traefik.http.routers.perfex.rule=Host(`perfex.seusite.com.br`)
        - traefik.http.services.perfex.loadbalancer.server.port=80
        - traefik.http.routers.perfex.service=perfex
        - traefik.http.routers.perfex.tls.certresolver=letsencryptresolver
        - traefik.http.routers.perfex.entrypoints=websecure
        - traefik.http.routers.perfex.tls=true
    networks:
      - SUA_NETWORK
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: SUA_SENHA
      MYSQL_DATABASE: perfexcrm
      MYSQL_USER: SEU_USUARIO
      MYSQL_PASSWORD: SUA_SENHA
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.4'
          memory: 256M
    networks:
      - SUA_NETWORK

networks:
  HuNet:
    external: true
    name: SUA_NETWORK

volumes:
  db_data:
    external: true
    name: db_data
